/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/q78qlbK
 */
import { AccordionTrigger, AccordionContent, AccordionItem, Accordion } from "@/components/ui/accordion"

export function FAQ() {
  return (
    <Accordion className="w-full mt-4" type="multiple">
      <AccordionItem value="item-0">
        <AccordionTrigger className="hover:underline-none">
          Что такое Onaychat?
        </AccordionTrigger>
        <AccordionContent className="text-muted-foreground">
          Onaychat - это решение для создания чатботов, которые могут отвечать на вопросы, помогать с навигацией по сайту и предоставлять информацию в реальном времени.
        </AccordionContent>
      </AccordionItem>

      <AccordionItem value="item-1">
        <AccordionTrigger className="hover:underline-none">
          Что такое OpenAI assistants?
        </AccordionTrigger>
        <AccordionContent className="text-muted-foreground">
          Assistants - это инструмент, который помогает разработчикам создавать мощные AI-ассистенты, способные выполнять различные задачи.
          Найти более подробную информацию <a href="https://platform.openai.com/docs/assistants/how-it-works" className="underline">здесь</a>.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-2">
        <AccordionTrigger className="hover:underline-none">
          Как чатбот адаптируется к сайту?
        </AccordionTrigger>
        <AccordionContent className="text-muted-foreground">
          Мы используем собственные парсеры, которые мы создали для извлечения контента, который затем используется для обучения чатбота.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-3">
        <AccordionTrigger className="hover:underline-none">
          Всегда ли доступен чатбот?
        </AccordionTrigger>
        <AccordionContent className="text-muted-foreground">
          Да, чатбот доступен 24/7, чтобы помочь с любыми вопросами в любое время.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-4">
        <AccordionTrigger className="hover:underline-none text-left">
          Какие вопросы можно задавать чатботу?
        </AccordionTrigger>
        <AccordionContent className="text-muted-foreground">
          Вы можете задавать чатботу вопросы о навигации по сайту, услугах, которые мы предоставляем, а также о технических проблемах.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem className="border-b-0" value="item-5">
        <AccordionTrigger className="hover:underline-none text-left">
          Заменяет ли чатбот человеческий сервис?
        </AccordionTrigger>
        <AccordionContent className="text-muted-foreground">
          Чатбот дополняет наш человеческий сервис, обрабатывая простые вопросы и проблемы, позволяя нашему человеческому персоналу сосредоточиться на более сложных запросах.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-6">
        <AccordionTrigger className="hover:underline-none">
          Какие модели поддерживаются чатботом?
        </AccordionTrigger>
        <AccordionContent className="text-muted-foreground">
          Мы поддерживаем модели GPT-3, GPT-4 и GPT-4o от OpenAI.
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  )
}
